return {
	["achieve1_1"] = {
		["id"] = "achieve1_1",
		["icon"] = "icon1",
		["des_id"] = "achieve1_1_des",
		["name"] = "累记登录天数2天",
		["achievenum"] = "Accumulated login days 2 times",
		["type"] = "login_num",
		["need"] = 2,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
	},
	["achieve1_2"] = {
		["id"] = "achieve1_2",
		["icon"] = "icon1",
		["des_id"] = "achieve1_2_des",
		["name"] = "累记登录天数4天",
		["achievenum"] = "Accumulated login days 4 times",
		["type"] = "login_num",
		["need"] = 4,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
	},
	["achieve1_3"] = {
		["id"] = "achieve1_3",
		["icon"] = "icon1",
		["des_id"] = "achieve1_3_des",
		["name"] = "累记登录天数6天",
		["achievenum"] = "Accumulated login days 6 times",
		["type"] = "login_num",
		["need"] = 6,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
	},
	["achieve1_4"] = {
		["id"] = "achieve1_4",
		["icon"] = "icon1",
		["des_id"] = "achieve1_4_des",
		["name"] = "累记登录天数8天",
		["achievenum"] = "Accumulated login days 8 times",
		["type"] = "login_num",
		["need"] = 8,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
	},
	["achieve1_5"] = {
		["id"] = "achieve1_5",
		["icon"] = "icon1",
		["des_id"] = "achieve1_5_des",
		["name"] = "累记登录天数10天",
		["achievenum"] = "Accumulated login days 10 times",
		["type"] = "login_num",
		["need"] = 10,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
	},
	["achieve2_1"] = {
		["id"] = "achieve2_1",
		["icon"] = "icon1",
		["des_id"] = "achieve2_1_des",
		["name"] = "等级达到2",
		["achievenum"] = "Level increased to 2",
		["type"] = "levelup",
		["need"] = 2,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve2_2"] = {
		["id"] = "achieve2_2",
		["icon"] = "icon1",
		["des_id"] = "achieve2_2_des",
		["name"] = "等级达到4",
		["achievenum"] = "Level increased to 4",
		["type"] = "levelup",
		["need"] = 4,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve2_3"] = {
		["id"] = "achieve2_3",
		["icon"] = "icon1",
		["des_id"] = "achieve2_3_des",
		["name"] = "等级达到6",
		["achievenum"] = "Level increased to 6",
		["type"] = "levelup",
		["need"] = 6,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve2_4"] = {
		["id"] = "achieve2_4",
		["icon"] = "icon1",
		["des_id"] = "achieve2_4_des",
		["name"] = "等级达到8",
		["achievenum"] = "Level increased to 8",
		["type"] = "levelup",
		["need"] = 8,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve2_5"] = {
		["id"] = "achieve2_5",
		["icon"] = "icon1",
		["des_id"] = "achieve2_5_des",
		["name"] = "等级达到10",
		["achievenum"] = "Level increased to 10",
		["type"] = "levelup",
		["need"] = 10,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve3_1"] = {
		["id"] = "achieve3_1",
		["icon"] = "icon1",
		["des_id"] = "achieve3_1_des",
		["name"] = "累计完成物件修复5次",
		["achievenum"] = "Repair of accumulated items completed 5 times",
		["type"] = "repair_num",
		["need"] = 5,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve3_2"] = {
		["id"] = "achieve3_2",
		["icon"] = "icon1",
		["des_id"] = "achieve3_2_des",
		["name"] = "累计完成物件修复10次",
		["achievenum"] = "Repair of accumulated items completed 10 times",
		["type"] = "repair_num",
		["need"] = 10,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve3_3"] = {
		["id"] = "achieve3_3",
		["icon"] = "icon1",
		["des_id"] = "achieve3_3_des",
		["name"] = "累计完成物件修复20次",
		["achievenum"] = "Repair of accumulated items completed 20 times",
		["type"] = "repair_num",
		["need"] = 20,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve3_4"] = {
		["id"] = "achieve3_4",
		["icon"] = "icon1",
		["des_id"] = "achieve3_4_des",
		["name"] = "累计完成物件修复50次",
		["achievenum"] = "Repair of accumulated items completed 50 times",
		["type"] = "repair_num",
		["need"] = 50,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve3_5"] = {
		["id"] = "achieve3_5",
		["icon"] = "icon1",
		["des_id"] = "achieve3_5_des",
		["name"] = "累计完成物件修复100次",
		["achievenum"] = "Repair of accumulated items completed 100 times",
		["type"] = "repair_num",
		["need"] = 100,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve4_1"] = {
		["id"] = "achieve4_1",
		["icon"] = "icon1",
		["des_id"] = "achieve4_1_des",
		["name"] = "累记销售额达到500$",
		["achievenum"] = "Accumulated sales reached 500$",
		["type"] = "sales_volume",
		["need"] = 500,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "goods_shelves",
	},
	["achieve4_2"] = {
		["id"] = "achieve4_2",
		["icon"] = "icon1",
		["des_id"] = "achieve4_2_des",
		["name"] = "累记销售额达到2000$",
		["achievenum"] = "Accumulated sales reached 2000$",
		["type"] = "sales_volume",
		["need"] = 2000,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "goods_shelves",
	},
	["achieve4_3"] = {
		["id"] = "achieve4_3",
		["icon"] = "icon1",
		["des_id"] = "achieve4_3_des",
		["name"] = "累记销售额达到5000$",
		["achievenum"] = "Accumulated sales reached 5000$",
		["type"] = "sales_volume",
		["need"] = 5000,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "goods_shelves",
	},
	["achieve4_4"] = {
		["id"] = "achieve4_4",
		["icon"] = "icon1",
		["des_id"] = "achieve4_4_des",
		["name"] = "累记销售额达到10000$",
		["achievenum"] = "Accumulated sales reached 10000$",
		["type"] = "sales_volume",
		["need"] = 10000,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "goods_shelves",
	},
	["achieve4_5"] = {
		["id"] = "achieve4_5",
		["icon"] = "icon1",
		["des_id"] = "achieve4_5_des",
		["name"] = "累记销售额达到20000$",
		["achievenum"] = "Accumulated sales reached 100000$",
		["type"] = "sales_volume",
		["need"] = 100000,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "goods_shelves",
	},
	["achieve5_1"] = {
		["id"] = "achieve5_1",
		["icon"] = "icon1",
		["des_id"] = "achieve5_1_des",
		["name"] = "累记观看视频20次",
		["achievenum"] = "Accumulated watch Video 20 times",
		["type"] = "watch_num",
		["need"] = 20,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve5_2"] = {
		["id"] = "achieve5_2",
		["icon"] = "icon1",
		["des_id"] = "achieve5_2_des",
		["name"] = "累记观看视频50次",
		["achievenum"] = "Accumulated watch Video 50 times",
		["type"] = "watch_num",
		["need"] = 50,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve5_3"] = {
		["id"] = "achieve5_3",
		["icon"] = "icon1",
		["des_id"] = "achieve5_3_des",
		["name"] = "累记观看视频100次",
		["achievenum"] = "Accumulated watch Video 100 times",
		["type"] = "watch_num",
		["need"] = 100,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve5_4"] = {
		["id"] = "achieve5_4",
		["icon"] = "icon1",
		["des_id"] = "achieve5_4_des",
		["name"] = "累记观看视频300次",
		["achievenum"] = "Accumulated watch Video 300 times",
		["type"] = "watch_num",
		["need"] = 300,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
	["achieve5_5"] = {
		["id"] = "achieve5_5",
		["icon"] = "icon1",
		["des_id"] = "achieve5_5_des",
		["name"] = "累记观看视频1000次",
		["achievenum"] = "Accumulated watch Video 1000 times",
		["type"] = "watch_num",
		["need"] = 1000,
		["reward"] = {
			[1] = {
				[1] = "item",
				[2] = "gold",
				[3] = "20",
			},
		},
		["jump"] = "recycling_market",
	},
}
