return {
	["daily_1"] = {
		["id"] = "daily_1",
		["des_id"] = "daily_1_des",
		["name"] = "每日观看视频广告3次",
		["achievenum"] = "Watch the video 3 times daily",
		["type"] = "watch_num",
		["need"] = 3,
		["active_point"] = 20,
		["jump"] = "recycling_market",
	},
	["daily_2"] = {
		["id"] = "daily_2",
		["des_id"] = "daily_2_des",
		["name"] = "每日排行榜点赞1次",
		["achievenum"] = "Likes the ranking 1 times daily",
		["type"] = "like",
		["need"] = 1,
		["active_point"] = 10,
		["jump"] = "rank",
	},
	["daily_3"] = {
		["id"] = "daily_3",
		["des_id"] = "daily_3_des",
		["name"] = "每日完成物品修复3次",
		["achievenum"] = "Complete repair 3 times daily",
		["type"] = "repair_num",
		["need"] = 3,
		["active_point"] = 20,
		["jump"] = "recycling_market",
	},
	["daily_4"] = {
		["id"] = "daily_4",
		["des_id"] = "daily_4_des",
		["name"] = "每日刷新回收列表1次",
		["achievenum"] = "Refresh recycling market list 1 times daily",
		["type"] = "refreshlist",
		["need"] = 1,
		["active_point"] = 10,
		["jump"] = "recycling_market",
	},
	["daily_5"] = {
		["id"] = "daily_5",
		["des_id"] = "daily_5_des",
		["name"] = "每日领取惊喜礼包1次",
		["achievenum"] = "Get the surprise gift 1 times daily",
		["type"] = "surprisegift",
		["need"] = 1,
		["active_point"] = 20,
		["jump"] = "recycling_market",
	},
	["daily_6"] = {
		["id"] = "daily_6",
		["des_id"] = "daily_6_des",
		["name"] = "每日使用立即出售1次",
		["achievenum"] = "Sell now 1 times daily",
		["type"] = "sellnow",
		["need"] = 3,
		["active_point"] = 10,
		["jump"] = "goods_shelves",
	},
	["daily_7"] = {
		["id"] = "daily_7",
		["des_id"] = "daily_7_des",
		["name"] = "每日使用三倍估值1次",
		["achievenum"] = "Triple valuation 1 times daily",
		["type"] = "triple",
		["need"] = 1,
		["active_point"] = 10,
		["jump"] = "recycling_market",
	},
	["daily_8"] = {
		["id"] = "daily_8",
		["des_id"] = "daily_8_des",
		["name"] = "每日喂养小狗1次",
		["achievenum"] = "Feed puppies 1 times daily",
		["type"] = "feed",
		["need"] = 1,
		["active_point"] = 10,
		["jump"] = "goods_shelves",
	},
}
