return {
	["goods1_1"] = {
		["id"] = "goods1_1",
		["des_id"] = "goods1_1_des",
		["buy"] = 5,
		["sell"] = 7,
		["bg_type"] = 1,
		["sell_time"] = 5,
		["sort"] = 1,
	},
	["goods1_2"] = {
		["id"] = "goods1_2",
		["des_id"] = "goods1_2_des",
		["buy"] = 5,
		["sell"] = 7,
		["bg_type"] = 2,
		["sell_time"] = 5,
		["sort"] = 2,
	},
	["goods1_3"] = {
		["id"] = "goods1_3",
		["des_id"] = "goods1_3_des",
		["buy"] = 5,
		["sell"] = 7,
		["bg_type"] = 3,
		["sell_time"] = 5,
		["sort"] = 3,
	},
	["goods1_4"] = {
		["id"] = "goods1_4",
		["des_id"] = "goods1_4_des",
		["buy"] = 5,
		["sell"] = 7,
		["bg_type"] = 4,
		["sell_time"] = 5,
		["sort"] = 4,
	},
	["goods2_1"] = {
		["id"] = "goods2_1",
		["des_id"] = "goods2_1_des",
		["buy"] = 7,
		["sell"] = 10,
		["bg_type"] = 1,
		["sell_time"] = 7,
		["sort"] = 5,
	},
	["goods2_2"] = {
		["id"] = "goods2_2",
		["des_id"] = "goods2_2_des",
		["buy"] = 7,
		["sell"] = 10,
		["bg_type"] = 2,
		["sell_time"] = 7,
		["sort"] = 6,
	},
	["goods2_3"] = {
		["id"] = "goods2_3",
		["des_id"] = "goods2_3_des",
		["buy"] = 7,
		["sell"] = 10,
		["bg_type"] = 3,
		["sell_time"] = 7,
		["sort"] = 7,
	},
	["goods2_4"] = {
		["id"] = "goods2_4",
		["des_id"] = "goods2_4_des",
		["buy"] = 7,
		["sell"] = 10,
		["bg_type"] = 4,
		["sell_time"] = 7,
		["sort"] = 8,
	},
	["goods3_1"] = {
		["id"] = "goods3_1",
		["des_id"] = "goods3_1_des",
		["buy"] = 10,
		["sell"] = 15,
		["bg_type"] = 1,
		["sell_time"] = 9,
		["sort"] = 9,
	},
	["goods3_2"] = {
		["id"] = "goods3_2",
		["des_id"] = "goods3_2_des",
		["buy"] = 10,
		["sell"] = 15,
		["bg_type"] = 2,
		["sell_time"] = 9,
		["sort"] = 10,
	},
	["goods3_3"] = {
		["id"] = "goods3_3",
		["des_id"] = "goods3_3_des",
		["buy"] = 10,
		["sell"] = 15,
		["bg_type"] = 3,
		["sell_time"] = 9,
		["sort"] = 11,
	},
	["goods3_4"] = {
		["id"] = "goods3_4",
		["des_id"] = "goods3_4_des",
		["buy"] = 10,
		["sell"] = 15,
		["bg_type"] = 4,
		["sell_time"] = 9,
		["sort"] = 12,
	},
	["goods4_1"] = {
		["id"] = "goods4_1",
		["des_id"] = "goods4_1_des",
		["buy"] = 15,
		["sell"] = 23,
		["bg_type"] = 1,
		["sell_time"] = 10,
		["sort"] = 13,
	},
	["goods4_2"] = {
		["id"] = "goods4_2",
		["des_id"] = "goods4_2_des",
		["buy"] = 15,
		["sell"] = 23,
		["bg_type"] = 2,
		["sell_time"] = 10,
		["sort"] = 14,
	},
	["goods4_3"] = {
		["id"] = "goods4_3",
		["des_id"] = "goods4_3_des",
		["buy"] = 15,
		["sell"] = 23,
		["bg_type"] = 3,
		["sell_time"] = 10,
		["sort"] = 15,
	},
	["goods4_4"] = {
		["id"] = "goods4_4",
		["des_id"] = "goods4_4_des",
		["buy"] = 15,
		["sell"] = 23,
		["bg_type"] = 4,
		["sell_time"] = 10,
		["sort"] = 16,
	},
	["goods5_1"] = {
		["id"] = "goods5_1",
		["des_id"] = "goods5_1_des",
		["buy"] = 20,
		["sell"] = 30,
		["bg_type"] = 1,
		["sell_time"] = 12,
		["sort"] = 17,
	},
	["goods5_2"] = {
		["id"] = "goods5_2",
		["des_id"] = "goods5_2_des",
		["buy"] = 20,
		["sell"] = 30,
		["bg_type"] = 2,
		["sell_time"] = 12,
		["sort"] = 18,
	},
	["goods5_3"] = {
		["id"] = "goods5_3",
		["des_id"] = "goods5_3_des",
		["buy"] = 20,
		["sell"] = 30,
		["bg_type"] = 3,
		["sell_time"] = 12,
		["sort"] = 19,
	},
	["goods5_4"] = {
		["id"] = "goods5_4",
		["des_id"] = "goods5_4_des",
		["buy"] = 20,
		["sell"] = 30,
		["bg_type"] = 4,
		["sell_time"] = 12,
		["sort"] = 20,
	},
	["goods6_1"] = {
		["id"] = "goods6_1",
		["des_id"] = "goods6_1_des",
		["buy"] = 30,
		["sell"] = 50,
		["bg_type"] = 1,
		["sell_time"] = 15,
		["sort"] = 21,
	},
	["goods6_2"] = {
		["id"] = "goods6_2",
		["des_id"] = "goods6_2_des",
		["buy"] = 30,
		["sell"] = 50,
		["bg_type"] = 2,
		["sell_time"] = 15,
		["sort"] = 22,
	},
	["goods6_3"] = {
		["id"] = "goods6_3",
		["des_id"] = "goods6_3_des",
		["buy"] = 30,
		["sell"] = 50,
		["bg_type"] = 3,
		["sell_time"] = 15,
		["sort"] = 23,
	},
	["goods6_4"] = {
		["id"] = "goods6_4",
		["des_id"] = "goods6_4_des",
		["buy"] = 30,
		["sell"] = 50,
		["bg_type"] = 4,
		["sell_time"] = 15,
		["sort"] = 24,
	},
	["goods7_1"] = {
		["id"] = "goods7_1",
		["des_id"] = "goods7_1_des",
		["buy"] = 50,
		["sell"] = 70,
		["bg_type"] = 1,
		["sell_time"] = 18,
		["sort"] = 25,
	},
	["goods7_2"] = {
		["id"] = "goods7_2",
		["des_id"] = "goods7_2_des",
		["buy"] = 50,
		["sell"] = 70,
		["bg_type"] = 2,
		["sell_time"] = 18,
		["sort"] = 26,
	},
	["goods7_3"] = {
		["id"] = "goods7_3",
		["des_id"] = "goods7_3_des",
		["buy"] = 50,
		["sell"] = 70,
		["bg_type"] = 3,
		["sell_time"] = 18,
		["sort"] = 27,
	},
	["goods7_4"] = {
		["id"] = "goods7_4",
		["des_id"] = "goods7_4_des",
		["buy"] = 50,
		["sell"] = 70,
		["bg_type"] = 4,
		["sell_time"] = 18,
		["sort"] = 28,
	},
	["goods8_1"] = {
		["id"] = "goods8_1",
		["des_id"] = "goods8_1_des",
		["buy"] = 70,
		["sell"] = 100,
		["bg_type"] = 1,
		["sell_time"] = 20,
		["sort"] = 29,
	},
	["goods8_2"] = {
		["id"] = "goods8_2",
		["des_id"] = "goods8_2_des",
		["buy"] = 70,
		["sell"] = 100,
		["bg_type"] = 2,
		["sell_time"] = 20,
		["sort"] = 30,
	},
	["goods8_3"] = {
		["id"] = "goods8_3",
		["des_id"] = "goods8_3_des",
		["buy"] = 70,
		["sell"] = 100,
		["bg_type"] = 3,
		["sell_time"] = 20,
		["sort"] = 31,
	},
	["goods8_4"] = {
		["id"] = "goods8_4",
		["des_id"] = "goods8_4_des",
		["buy"] = 70,
		["sell"] = 100,
		["bg_type"] = 4,
		["sell_time"] = 20,
		["sort"] = 32,
	},
	["goods9_1"] = {
		["id"] = "goods9_1",
		["des_id"] = "goods9_1_des",
		["buy"] = 100,
		["sell"] = 150,
		["bg_type"] = 1,
		["sell_time"] = 25,
		["sort"] = 33,
	},
	["goods9_2"] = {
		["id"] = "goods9_2",
		["des_id"] = "goods9_2_des",
		["buy"] = 100,
		["sell"] = 150,
		["bg_type"] = 2,
		["sell_time"] = 25,
		["sort"] = 34,
	},
	["goods9_3"] = {
		["id"] = "goods9_3",
		["des_id"] = "goods9_3_des",
		["buy"] = 100,
		["sell"] = 150,
		["bg_type"] = 3,
		["sell_time"] = 25,
		["sort"] = 35,
	},
	["goods9_4"] = {
		["id"] = "goods9_4",
		["des_id"] = "goods9_4_des",
		["buy"] = 100,
		["sell"] = 150,
		["bg_type"] = 4,
		["sell_time"] = 25,
		["sort"] = 36,
	},
	["goods10_1"] = {
		["id"] = "goods10_1",
		["des_id"] = "goods10_1_des",
		["buy"] = 150,
		["sell"] = 250,
		["bg_type"] = 1,
		["sell_time"] = 30,
		["sort"] = 37,
	},
	["goods10_2"] = {
		["id"] = "goods10_2",
		["des_id"] = "goods10_2_des",
		["buy"] = 150,
		["sell"] = 250,
		["bg_type"] = 2,
		["sell_time"] = 30,
		["sort"] = 38,
	},
	["goods10_3"] = {
		["id"] = "goods10_3",
		["des_id"] = "goods10_3_des",
		["buy"] = 150,
		["sell"] = 250,
		["bg_type"] = 3,
		["sell_time"] = 30,
		["sort"] = 39,
	},
	["goods10_4"] = {
		["id"] = "goods10_4",
		["des_id"] = "goods10_4_des",
		["buy"] = 150,
		["sell"] = 250,
		["bg_type"] = 4,
		["sell_time"] = 30,
		["sort"] = 40,
	},
}
