return {
	["saw_1"] = {
		["id"] = "saw_1",
		["point_tool"] = "hand_saw_1",
		["des_id"] = "saw_1_des",
		["name"] = "多余木块",
		["e_name"] = "saw",
		["class"] = 1,
		["price"] = 1,
		["exp"] = 1,
		["star"] = 3,
	},
	["nail_1"] = {
		["id"] = "nail_1",
		["point_tool"] = "pincer_pliers_1",
		["des_id"] = "nail_1_des",
		["name"] = "钉子",
		["e_name"] = "nail",
		["class"] = 1,
		["price"] = 2,
		["exp"] = 2,
		["star"] = 2,
	},
	["iron_wire_1"] = {
		["id"] = "iron_wire_1",
		["point_tool"] = "nipper_pliers_1",
		["des_id"] = "iron_wire_1_des",
		["name"] = "生锈铁丝",
		["e_name"] = "iron_wire",
		["class"] = 1,
		["price"] = 3,
		["exp"] = 3,
		["star"] = 3,
	},
	["flip_surface"] = {
		["id"] = "flip_surface",
		["point_tool"] = "wood_shave_1",
		["des_id"] = "flip_surface_des",
		["name"] = "凹凸不平颗粒",
		["e_name"] = "flip",
		["class"] = 1,
		["price"] = 4,
		["exp"] = 4,
		["star"] = 3,
	},
	["pull_screw_1"] = {
		["id"] = "pull_screw_1",
		["point_tool"] = "driver_1",
		["des_id"] = "pull_screw_1_des",
		["name"] = "取螺丝",
		["e_name"] = "pull_screw",
		["class"] = 1,
		["price"] = 5,
		["exp"] = 5,
		["star"] = 2,
	},
	["put_screw_1"] = {
		["id"] = "put_screw_1",
		["point_tool"] = "driver_1",
		["des_id"] = "put_screw_1_des",
		["name"] = "扭螺丝",
		["e_name"] = "put_screw",
		["class"] = 1,
		["price"] = 5,
		["exp"] = 5,
		["star"] = 2,
	},
	["break_1"] = {
		["id"] = "break_1",
		["point_tool"] = "claw_hammer_1",
		["des_id"] = "break_1_des",
		["name"] = "拆除",
		["e_name"] = "break",
		["class"] = 1,
		["price"] = 6,
		["exp"] = 6,
		["star"] = 3,
	},
	["sanding_1"] = {
		["id"] = "sanding_1",
		["point_tool"] = "sanding_machine_1",
		["des_id"] = "sanding_1_des",
		["name"] = "打磨",
		["e_name"] = "sanding",
		["class"] = 1,
		["price"] = 7,
		["exp"] = 7,
		["star"] = 3,
	},
	["oil_1"] = {
		["id"] = "oil_1",
		["point_tool"] = "wax_oil_1",
		["des_id"] = "oil_1_des",
		["name"] = "打蜡",
		["e_name"] = "oil",
		["class"] = 1,
		["price"] = 8,
		["exp"] = 8,
		["star"] = 5,
	},
	["polish_1"] = {
		["id"] = "polish_1",
		["point_tool"] = "plishing_machine_1",
		["des_id"] = "polish_1_des",
		["name"] = "抛光",
		["e_name"] = "polish",
		["class"] = 1,
		["price"] = 9,
		["exp"] = 9,
		["star"] = 5,
	},
	["colour_1"] = {
		["id"] = "colour_1",
		["point_tool"] = "brush_1",
		["des_id"] = "colour_1_des",
		["name"] = "颜料",
		["e_name"] = "colour",
		["class"] = 1,
		["price"] = 10,
		["exp"] = 10,
		["star"] = 5,
	},
	["wood_dash_1"] = {
		["id"] = "wood_dash_1",
		["point_tool"] = "filler_1",
		["des_id"] = "wood_dash_1_des",
		["name"] = "缺口",
		["e_name"] = "wood_dash",
		["class"] = 1,
		["price"] = 11,
		["exp"] = 11,
		["star"] = 3,
	},
	["lack_1"] = {
		["id"] = "lack_1",
		["point_tool"] = "hammer_1",
		["des_id"] = "lack_1_des",
		["name"] = "缺部位",
		["e_name"] = "lack",
		["class"] = 1,
		["price"] = 12,
		["exp"] = 12,
		["star"] = 3,
	},
	["clear_1"] = {
		["id"] = "clear_1",
		["point_tool"] = "feather_duster_1",
		["des_id"] = "clear_1_des",
		["name"] = "清理",
		["e_name"] = "clear",
		["class"] = 1,
		["price"] = 13,
		["exp"] = 13,
		["star"] = 5,
	},
	["a_1"] = {
		["id"] = "a_1",
		["point_tool"] = "spanner_1",
		["des_id"] = "a_1_des",
		["name"] = "螺母",
		["e_name"] = "a",
		["class"] = 1,
		["price"] = 14,
		["exp"] = 14,
		["star"] = 2,
	},
	["b_1"] = {
		["id"] = "b_1",
		["point_tool"] = "shears_1",
		["des_id"] = "b_1_des",
		["name"] = "修剪",
		["e_name"] = "b",
		["class"] = 1,
		["price"] = 15,
		["exp"] = 15,
		["star"] = 3,
	},
	["c_1"] = {
		["id"] = "c_1",
		["point_tool"] = "nicking_tool_1",
		["des_id"] = "c_1_des",
		["name"] = "木刻",
		["e_name"] = "c",
		["class"] = 1,
		["price"] = 16,
		["exp"] = 16,
		["star"] = 5,
	},
}
