return {
	["hand_saw_1"] = {
		["id"] = "hand_saw_1",
		["des_id"] = "hand_saw_1_des",
		["icon_res"] = "saw",
		["name"] = "手锯",
		["e_name"] = "hand_saw",
		["lv"] = 1,
		["unlock"] = 2,
		["des"] = "去除多余木块",
		["operation_info"] = "接近提示的多余位置，左右滑动数下后多余位置掉落",
	},
	["pincer_pliers_1"] = {
		["id"] = "pincer_pliers_1",
		["des_id"] = "pincer_pliers_1_des",
		["name"] = "老虎钳",
		["e_name"] = "pincer_pliers",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "拔钉子",
		["operation_info"] = "接近钉子自动掐住然后玩家用力拔出即可",
	},
	["nipper_pliers_1"] = {
		["id"] = "nipper_pliers_1",
		["des_id"] = "nipper_pliers_1_des",
		["name"] = "尖嘴钳",
		["e_name"] = "nipper_pliers",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "拔铁丝",
	},
	["wood_shave_1"] = {
		["id"] = "wood_shave_1",
		["des_id"] = "wood_shave_1_des",
		["icon_res"] = "wood_shave",
		["name"] = "木刨",
		["e_name"] = "wood_shave",
		["lv"] = 1,
		["unlock"] = 8,
		["des"] = "刨平凹凸",
	},
	["driver_1"] = {
		["id"] = "driver_1",
		["des_id"] = "driver_1_des",
		["icon_res"] = "electric_drill",
		["name"] = "电动螺丝",
		["e_name"] = "driver",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "取/放螺丝",
		["operation_info"] = "接近螺丝位置，自动吸附，玩家向提示方向滑动即可",
	},
	["claw_hammer_1"] = {
		["id"] = "claw_hammer_1",
		["des_id"] = "claw_hammer_1_des",
		["icon_res"] = "claw_hammer",
		["name"] = "羊角锤",
		["e_name"] = "claw_hammer",
		["lv"] = 1,
		["unlock"] = 6,
		["des"] = "拆多余部件",
		["operation_info"] = "接近拆除位置，自动吸附，玩家用力过快会导致手滑，需要匀速",
	},
	["sanding_machine_1"] = {
		["id"] = "sanding_machine_1",
		["des_id"] = "sanding_machine_1_des",
		["icon_res"] = "sanding_machine",
		["name"] = "砂纸机",
		["e_name"] = "sanding_machine",
		["lv"] = 1,
		["unlock"] = 3,
		["des"] = "去除表面污渍",
	},
	["wax_oil_1"] = {
		["id"] = "wax_oil_1",
		["des_id"] = "wax_oil_1_des",
		["name"] = "蜡油",
		["e_name"] = "wax_oil",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "打蜡",
		["operation_info"] = "变的发光",
	},
	["plishing_machine_1"] = {
		["id"] = "plishing_machine_1",
		["des_id"] = "plishing_machine_1_des",
		["name"] = "抛光机",
		["e_name"] = "plishing_machine",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "抛光",
		["operation_info"] = "变好看",
	},
	["brush_1"] = {
		["id"] = "brush_1",
		["des_id"] = "brush_1_des",
		["icon_res"] = "brush",
		["name"] = "颜料刷",
		["e_name"] = "brush",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "上色",
		["operation_info"] = "刷颜料",
	},
	["filler_1"] = {
		["id"] = "filler_1",
		["des_id"] = "filler_1_des",
		["icon_res"] = "storage_sign_05",
		["name"] = "木胶粉",
		["e_name"] = "filler",
		["lv"] = 1,
		["unlock"] = 7,
		["des"] = "填补裂痕",
		["operation_info"] = "修复裂痕",
	},
	["hammer_1"] = {
		["id"] = "hammer_1",
		["des_id"] = "hammer_1_des",
		["icon_res"] = "hammer",
		["name"] = "安全锤",
		["e_name"] = "hammer",
		["lv"] = 1,
		["unlock"] = 4,
		["des"] = "修复缺失位置",
		["operation_info"] = "玩家在提示的位置上进行点击即可修复，弹出修复百分比，每次点击需要消耗少量金币",
	},
	["feather_duster_1"] = {
		["id"] = "feather_duster_1",
		["des_id"] = "feather_duster_1_des",
		["icon_res"] = "duster",
		["name"] = "吹、气囊",
		["e_name"] = "feather_duster",
		["lv"] = 1,
		["unlock"] = 5,
		["des"] = "清理",
		["operation_info"] = "去掉蜘蛛网、灰尘等",
	},
	["spanner_1"] = {
		["id"] = "spanner_1",
		["des_id"] = "spanner_1_des",
		["name"] = "活动扳手",
		["e_name"] = "spanner",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "去除螺母",
		["operation_info"] = "接近螺母，自动吸附，旋转扳手可以拆卸。",
	},
	["shears_1"] = {
		["id"] = "shears_1",
		["des_id"] = "shears_1_des",
		["name"] = "剪刀",
		["e_name"] = "shears",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "修剪多余部分",
		["operation_info"] = "多用于皮质、布质、纸质等材料",
	},
	["nicking_tool_1"] = {
		["id"] = "nicking_tool_1",
		["des_id"] = "nicking_tool_1_des",
		["icon_res"] = "chisel",
		["name"] = "凿子",
		["e_name"] = "nicking_tool",
		["lv"] = 1,
		["unlock"] = 1,
		["des"] = "修剪多余部分",
		["operation_info"] = "多用于木质、石制",
	},
}
